name = "<YOUR-API-NAME>"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "local"
EMAIL_VERIFICATION_CODE_LIMIT = 3 # change this to whatever is appropriate

[[d1_databases]]
binding = "DB"
# These db names should match up with what's in backend/package.json
database_name = "<YOUR-APP-NAME>-db-local"
database_id = "asdf"

[[kv_namespaces]]
binding = "KV"
id = ""

[env.preview]
name = "<YOUR-PREVIEW-API-NAME>"
# Optionally assign custom domain, I believe cloudflare handles the hosting automatically (assuming your cloudflare account owns the domain)
# routes = [{ pattern = "<YOUR-DOMAIN>", custom_domain = true }]

[[env.preview.d1_databases]]
binding = "DB"
# These db names should match up with what's in backend/package.json
database_name = "<YOUR-APP-NAME>-db-preview"
database_id = "<YOUR-PREVIEW-DB-ID>"

[env.preview.vars]
ENVIRONMENT = "preview"
LOG_LEVEL = "silent"

[[env.preview.kv_namespaces]]
binding = "KV"
id = "<YOUR-PREVIEW-KV-ID>"

[env.prod]
name = "<YOUR-PROD-API-NAME>"
# routes = [{ pattern = "<your-prod-api-url>", custom_domain = true }]

[[env.prod.d1_databases]]
binding = "DB"
# These db names should match up with what's in backend/package.json
database_name = "<YOUR-APP-NAME>-db"
database_id = "<YOUR-PROD-DB-ID>"

[[env.prod.kv_namespaces]]
binding = "KV"
id = "<YOUR-PROD-DB-ID>"

[env.prod.vars]
ENVIRONMENT = "production"
