name = "<YOUR-API-NAME>"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "<YOUR-HYPERDRIVE-ID>"
localConnectionString = "<YOUR-HYPERDRIVE-CONNECTION-STRING>" # (same as what you used to generate hyperdrive

[[unsafe.bindings]]
name = "AUTHED_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 150, period = 60 }

[[unsafe.bindings]]
name = "BASE_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1002"
simple = { limit = 15, period = 10 }

[vars]
LOG_LEVEL = "error"

[[kv_namespaces]]
binding = "KV"
id = ""

###### PREVIEW

[[env.preview.unsafe.bindings]]
name = "AUTHED_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1011"
simple = { limit = 150, period = 60 }

[[env.preview.unsafe.bindings]]
name = "BASE_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1012"
simple = { limit = 15, period = 10 }

[env.preview]
name = "<YOUR-PREVIEW-API-NAME>"
routes = [{ pattern = "<YOUR-PREVIEW-API-URL>", custom_domain = true }]

[env.preview.vars]
ENVIRONMENT = "preview"
EMAIL_VERIFICATION_CODE_LIMIT = 3

[[env.preview.kv_namespaces]]
binding = "KV"
id = "<YOUR-PREVIEW-KV-ID>"

###### PROD

[[env.prod.unsafe.bindings]]
name = "AUTHED_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1021"
simple = { limit = 150, period = 60 }

[[env.prod.unsafe.bindings]]
name = "BASE_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1022"
simple = { limit = 15, period = 10 }

[env.prod]
name = "<YOUR-PROD-API-NAME>"
routes = [{ pattern = "<YOUR-PROD-API-URL>", custom_domain = true }]

[[env.prod.kv_namespaces]]
binding = "KV"
id = "<YOUR-PROD-KV-ID>"

[env.prod.vars]
ENVIRONMENT = "prod"
EMAIL_VERIFICATION_CODE_LIMIT = 3
